server:
  port: 8989
  jetty:
    acceptors: 2
    selectors: 4
    request-header-size: 8192
    max-http-form-post-size: 1048576
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 465700
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: admin,security-admin

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
springfox:
  documentation:
    swagger:
      v2:
        path: /api/v2/api-docs


mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: delFlag  # 指定逻辑删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto  # id自增
  configuration:
    map-underscore-to-camel-case: true
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
    helperDialect: mysql
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true


pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true




project:
  folder:  E:/logs/app

oss:
  accessKey: 33hzmmqPOwSsWXDjOVPI_8Vxd8CIEYxIuX-4d-Xm
  secreKey: 1yX5LrMf15Y93IpVgB6gVF8tn2DUg1Qq2g7VO_zc
  bucket: blog
swagger:
  basePackage: cn.wenzhuo4657.blog.admin.controller



