server:
  port: 7090
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 465700
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0


mybatis-plus:
  global-config:
    banner: false
project:
  folder:  E:/logs/app




