server:
  port: 7777
  jetty:
    acceptors: 2
    selectors: 4
    request-header-size: 8192
    max-http-form-post-size: 1048576
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 465700
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0


mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: delFlag  # 指定逻辑删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
    helperDialect: mysql
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true



project:
  folder:  E:/logs/app






